name: random_frame
description: "Random Frame for Warpcast"

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7
  intl: ^0.20.2
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  equatable: ^2.0.5
  theme_provider: ^0.6.0
  google_fonts: ^6.2.1
  responsive_framework: ^1.1.0
  go_router: ^9.0.3
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.3.0
  screenshot: ^3.0.0
  supabase_flutter: ^2.0.0
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  firebase_performance: ^0.10.1+4
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - env
